service: elm-serverless-demo

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    dontPrintOutput: true

functions:
  routing:
    handler: src/Routing/api.handler
    events:
      - http:
          integration: lambda-proxy
          path: /routing
          method: ANY
      - http:
          integration: lambda-proxy
          path: /routing/{proxy+} # Lambda Proxy Integration
          method: ANY
