service: elm-serverless-demo

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-identity:*,
        - cognito-idp:*,
        - cognito-sync:*,
        - iam:ListRoles,
        - iam:ListOpenIdConnectProviders,
        - sns:ListPlatformApplications
      Resource: '*'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    dontPrintOutput: true

functions:
  routing:
    handler: src/Routing/api.handler
    events:
      - http:
          integration: lambda-proxy
          path: /routing
          method: ANY
      - http:
          integration: lambda-proxy
          path: /routing/{proxy+}
          method: ANY
